# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sinatra-formhelpers-ng"
  s.version = "1.11.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["twilson63", "Nate Wiger", "Cymen Vig", "Ben Fenner"]
  s.date = "2013-12-18"
  s.description = "Simple, lightweight form helpers for Sinatra."
  s.email = "fenfam@sc.rr.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/sinatra/form_helpers.rb",
    "sinatra-formhelpers-ng.gemspec",
    "spec/form_helpers_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/BenFenner/sinatra-formhelpers-ng"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Form helpers for Sinatra"

  # If you want to use this gem, use updated stuff.
  s.add_runtime_dependency(%q<rack-test>, [">= 0"])
  s.add_development_dependency(%q<bacon>, [">= 0"], [">= 0"])
end

